[build]
  # Directorio que contiene los archivos estáticos generados
  publish = "out"
  
  # Comando que ejecuta el build
  command = "npm run build:prod"

# Variables de entorno para el build
[build.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_URL = "https://marketingsimulator.netlify.app"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
